language: c++
install: make git libelf-dev gcc-avr avr-libc freeglut3-dev elfutils libelf1 libglib2.0-dev gdb-avr
sudo: enabled
script: git clone https://github.com/buserror/simavr.git && cd ./simavr && make && sudo make install && sudo ldconfig && cd - && make
